MedicoMVC/Controllers/EspecialidadController.cs
using MedicoMVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MedicoMVC.Controllers
{
    public class EspecialidadController : Controller
    {
        private readonly IEspecialidadesServices _Services;

        public EspecialidadController(IEspecialidadesServices services)
        {
            _Services = services;
        }
        public async Task<IActionResult> Index()
        {
            var resoponse = await _Services.ListarEspecialidadAsync();
            return View(resoponse.Data);
        }
    }
}

MedicoMVC/Controllers/MedicoController.cs
using MedicoMVC.Models.Request;
using MedicoMVC.Models.ViewModels;
using MedicoMVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Signing;


namespace MedicoMVC.Controllers
{
    public class MedicoController : Controller
    {
        private readonly IMedicoServices _MedicoServices;
        private readonly IEspecialidadesServices _EspecialidadServices;

        public MedicoController(IMedicoServices medicoServices,
            IEspecialidadesServices especialidadServices)
        {
            _MedicoServices = medicoServices;
            _EspecialidadServices = especialidadServices;
        }

        public async Task<IActionResult> Index([FromQuery]string? nombreCompleto,[FromQuery] DateTime? fechaIngresoInicio, [FromQuery] DateTime? fechaIngresoFin, [FromQuery] string? matricula,
            [FromQuery]string? cedulaProfecional, [FromQuery] int? especialidadSeleccionada)
        {
            var listaEspecialidades = await _EspecialidadServices.ListarEspecialidadAsync(); 
            var response = await _MedicoServices.ListarMedicosAsync(nombreCompleto, fechaIngresoInicio, fechaIngresoFin, matricula, cedulaProfecional, especialidadSeleccionada);
            ViewBag.nombreCompleto = nombreCompleto;
            ViewBag.fechaIngresoInicio = fechaIngresoInicio;
            ViewBag.fechaIngresoFin = fechaIngresoInicio;
            ViewBag.matricula = matricula;
            ViewBag.cedulaProfecional = cedulaProfecional;
            ViewBag.especialidadSeleccionada = especialidadSeleccionada;

            var model = new SearchMedicoViewModel()
            {
                NombreCompleto = nombreCompleto,
                FechaIngresoInicio = fechaIngresoInicio,
                FechaIngresoFin = fechaIngresoFin,
                Matricula = matricula,
                CedulaProfecional = cedulaProfecional,
                Especialidades = listaEspecialidades.Data,
                EspecialidadSeleccionada = especialidadSeleccionada,
                Medicos = response.Data
            };

            return View(model);
        }


        public async Task<IActionResult> Crear()
        {
            var model = new MedicoViewModel();

            var listaEspecialidades = await _EspecialidadServices.ListarEspecialidadAsync();
            
            model.Especialidades = listaEspecialidades.Data;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Crear(MedicoViewModel model)
        {


            var response = await _MedicoServices.InsertarAsync(new MedicoDTORequest()
            {
                NombreCompleto = model.NombreCompleto,
                Matricula = model.Matricula,
                CedulaProfecional = model.CedulaProfecional,
                EspecialidadId = model.EspecialidadSeleccionada
                
            });

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Editar(int id)
        {
            var entity = await _MedicoServices.FinMedicoByIdAsync(id);
            var listaEspecialidades = await _EspecialidadServices.ListarEspecialidadAsync();

            if(entity is  null)
            {
                return RedirectToAction(nameof(Index));
            }
            var model = new MedicoViewModel()
            {
                MedicoId = entity.Data.MedicoId,
                NombreCompleto = entity.Data.NombreCompleto,
                Matricula = entity.Data.Matricula,
                CedulaProfecional = entity.Data.CedulaProfecional,
                Especialidades = listaEspecialidades.Data,
                NombreEspecialidad = entity.Data.Especialidad.NombreEspecialidad
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Editar(MedicoViewModel model)
        {

            await _MedicoServices.UpdatearAsync(model.MedicoId,
                new MedicoDTORequest()
                {
                    NombreCompleto = model.NombreCompleto,
                    Matricula = model.Matricula,
                    CedulaProfecional = model.CedulaProfecional,
                    EspecialidadId = model.EspecialidadSeleccionada,
                });

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Eliminar(int id)
        {
            var existeMedico = await _MedicoServices.FinMedicoByIdAsync(id);

            if(existeMedico is  null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new MedicoViewModel()
            {
                MedicoId = id
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(MedicoViewModel model)
        {
            var medico = await _MedicoServices.EliminarAsync(model.MedicoId);

            return RedirectToAction(nameof(Index));


        }

        public async Task<IActionResult> MedicosEliminados()
        {
            var listaMedicosEliminados = await _MedicoServices.ListarEliminadosAsync();

            return View(listaMedicosEliminados.Data);
        }

        public async Task<IActionResult> Reactivar(int id)
        {
            var existeMedico = await _MedicoServices.FinMedicoByIdAsync(id);

             if(existeMedico is null)
             {
                return RedirectToAction(nameof(Index));
             }

            var model = new MedicoViewModel()
            {
                MedicoId = id
            };

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> Reactivar(MedicoViewModel model)
        {
            var reactivarMedico = await _MedicoServices.ReactivarAsync(model.MedicoId);

            return RedirectToAction(nameof(MedicosEliminados));
        }

        


    }
}

MedicoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedicoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MedicoMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="Head">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedicoMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medico" asp-action="Index">Medicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Especialidad" asp-action="Index">Especialidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medico" asp-action="MedicosEliminados">Medicos Eliminados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MedicoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>