MedicoMVC/Models/ViewModels/MedicoViewModel.cs
using MedicoMVC.Models.Request;
using MedicoMVC.Models.Response;
using System.ComponentModel.DataAnnotations;

namespace MedicoMVC.Models.ViewModels
{
    public class MedicoViewModel
    {
        public int MedicoId { get; set; }
        [Display(Name = "Nombre Completo")]
        public string NombreCompleto { get; set; } = default!;
        public string Matricula { get; set; } = default!;
        [Display(Name = "Cedula Profecional")] 
        public string CedulaProfecional { get; set; } = default!;
        public ICollection<EspecialidadDTOResponse> Especialidades { get; set; } = default!;
        [Display(Name ="Especialidad")]
        public int EspecialidadSeleccionada { get; set; }
        public string NombreEspecialidad { get; set; } = default!;
    }
}

MedicoMVC/Controllers/MedicoController.cs
using MedicoMVC.Models.Request;
using MedicoMVC.Models.ViewModels;
using MedicoMVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using NuGet.Packaging.Signing;


namespace MedicoMVC.Controllers
{
    public class MedicoController : Controller
    {
        private readonly IMedicoServices _MedicoServices;
        private readonly IEspecialidadesServices _EspecialidadServices;

        public MedicoController(IMedicoServices medicoServices,
            IEspecialidadesServices especialidadServices)
        {
            _MedicoServices = medicoServices;
            _EspecialidadServices = especialidadServices;
        }

        public async Task<IActionResult> Index([FromQuery]string? nombreCompleto,[FromQuery] DateTime? fechaIngresoInicio, [FromQuery] DateTime? fechaIngresoFin, [FromQuery] string? matricula,
            [FromQuery]string? cedulaProfecional, [FromQuery] int? especialidadSeleccionada)
        {
            var listaEspecialidades = await _EspecialidadServices.ListarEspecialidadAsync(); 
            var response = await _MedicoServices.ListarMedicosAsync(nombreCompleto, fechaIngresoInicio, fechaIngresoFin, matricula, cedulaProfecional, especialidadSeleccionada);
            ViewBag.nombreCompleto = nombreCompleto;
            ViewBag.fechaIngresoInicio = fechaIngresoInicio;
            ViewBag.fechaIngresoFin = fechaIngresoInicio;
            ViewBag.matricula = matricula;
            ViewBag.cedulaProfecional = cedulaProfecional;
            ViewBag.especialidadSeleccionada = especialidadSeleccionada;

            var model = new SearchMedicoViewModel()
            {
                NombreCompleto = nombreCompleto,
                FechaIngresoInicio = fechaIngresoInicio,
                FechaIngresoFin = fechaIngresoFin,
                Matricula = matricula,
                CedulaProfecional = cedulaProfecional,
                Especialidades = listaEspecialidades.Data,
                EspecialidadSeleccionada = especialidadSeleccionada,
                Medicos = response.Data
            };

            return View(model);
        }


        public async Task<IActionResult> Crear()
        {
            var model = new MedicoViewModel();

            var listaEspecialidades = await _EspecialidadServices.ListarEspecialidadAsync();
            
            model.Especialidades = listaEspecialidades.Data;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Crear(MedicoViewModel model)
        {


            var response = await _MedicoServices.InsertarAsync(new MedicoDTORequest()
            {
                NombreCompleto = model.NombreCompleto,
                Matricula = model.Matricula,
                CedulaProfecional = model.CedulaProfecional,
                EspecialidadId = model.EspecialidadSeleccionada
                
            });

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Editar(int id)
        {
            var entity = await _MedicoServices.FinMedicoByIdAsync(id);
            var listaEspecialidades = await _EspecialidadServices.ListarEspecialidadAsync();

            if(entity is  null)
            {
                return RedirectToAction(nameof(Index));
            }
            var model = new MedicoViewModel()
            {
                MedicoId = entity.Data.MedicoId,
                NombreCompleto = entity.Data.NombreCompleto,
                Matricula = entity.Data.Matricula,
                CedulaProfecional = entity.Data.CedulaProfecional,
                Especialidades = listaEspecialidades.Data,
                NombreEspecialidad = entity.Data.Especialidad.NombreEspecialidad
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Editar(MedicoViewModel model)
        {

            await _MedicoServices.UpdatearAsync(model.MedicoId,
                new MedicoDTORequest()
                {
                    NombreCompleto = model.NombreCompleto,
                    Matricula = model.Matricula,
                    CedulaProfecional = model.CedulaProfecional,
                    EspecialidadId = model.EspecialidadSeleccionada,
                });

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Eliminar(int id)
        {
            var existeMedico = await _MedicoServices.FinMedicoByIdAsync(id);

            if(existeMedico is  null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new MedicoViewModel()
            {
                MedicoId = id
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(MedicoViewModel model)
        {
            var medico = await _MedicoServices.EliminarAsync(model.MedicoId);

            return RedirectToAction(nameof(Index));


        }

        public async Task<IActionResult> MedicosEliminados()
        {
            var listaMedicosEliminados = await _MedicoServices.ListarEliminadosAsync();

            return View(listaMedicosEliminados.Data);
        }

        public async Task<IActionResult> Reactivar(int id)
        {
            var existeMedico = await _MedicoServices.FinMedicoByIdAsync(id);

             if(existeMedico is null)
             {
                return RedirectToAction(nameof(Index));
             }

            var model = new MedicoViewModel()
            {
                MedicoId = id
            };

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> Reactivar(MedicoViewModel model)
        {
            var reactivarMedico = await _MedicoServices.ReactivarAsync(model.MedicoId);

            return RedirectToAction(nameof(MedicosEliminados));
        }

        


    }
}

MedicoMVC/Controllers/MedicoPruebaController.cs
using MedicoMVC.Models.Request;
using MedicoMVC.Models.Response;
using MedicoMVC.Models.ViewModels;
using MedicoMVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace MedicoMVC.Controllers
{
    public class MedicoPruebaController: Controller
    {
        private readonly IMedicoServices _medicoServices;
        private readonly IEspecialidadesServices _especiañidadServices;

        public MedicoPruebaController(IMedicoServices medicoServices,
            IEspecialidadesServices especiañidadServices)
        {
            _medicoServices = medicoServices;
            _especiañidadServices = especiañidadServices;
        }
        public async Task<IActionResult> Index([FromQuery] string? nombreCompleto, [FromQuery] DateTime? fechaIngresoInicio, [FromQuery] DateTime? fechaIngresoFin, 
            [FromQuery] string? matricula,[FromQuery] string? cedulaProfecional, [FromQuery] int? especialidadSeleccionada)
        {
            var listaEspecialidades = await _especiañidadServices.ListarEspecialidadAsync();
            var response = await _medicoServices.ListarMedicosAsync(nombreCompleto, fechaIngresoInicio, fechaIngresoFin, matricula, cedulaProfecional, especialidadSeleccionada);
            ViewBag.nombreCompleto = nombreCompleto;
            ViewBag.fechaIngresoInicio = fechaIngresoInicio;
            ViewBag.fechaIngresoFin = fechaIngresoFin;
            ViewBag.matricula = matricula;
            ViewBag.cedulaProfecional = cedulaProfecional;
            ViewBag.especialidadSeleccionada = especialidadSeleccionada;

            var model = new SearchMedicoViewModel()
            {
                NombreCompleto = nombreCompleto,
                FechaIngresoInicio = fechaIngresoInicio,
                FechaIngresoFin = fechaIngresoFin,
                Matricula = matricula,
                CedulaProfecional = cedulaProfecional,
                Especialidades = listaEspecialidades.Data,
                EspecialidadSeleccionada = especialidadSeleccionada,
                Medicos = response.Data
            };

            return View(model);
        }

        public async Task<IActionResult> Crear()
        {
            var model = new MedicoViewModel();

            var listaDeEspecialidades = await _especiañidadServices.ListarEspecialidadAsync();

            model.Especialidades = listaDeEspecialidades.Data;

            return View(model);


        }

        [HttpPost]
        public async Task<IActionResult> Crear(MedicoViewModel model)
        {

             


            var response = await _medicoServices.InsertarAsync(new Models.Request.MedicoDTORequest()
            {
                NombreCompleto = model.NombreCompleto,
                Matricula = model.Matricula,
                CedulaProfecional = model.CedulaProfecional,
                EspecialidadId = model.EspecialidadSeleccionada
            });

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Editar(int id)
        {

            var listaEspecialidades = await _especiañidadServices.ListarEspecialidadAsync();
            var medico = await _medicoServices.FinMedicoByIdAsync(id);

            var model = new MedicoViewModel()
            {
                MedicoId = medico.Data.MedicoId,
                NombreCompleto = medico.Data.NombreCompleto,
                Matricula = medico.Data.Matricula,
                CedulaProfecional = medico.Data.CedulaProfecional,
                Especialidades = listaEspecialidades.Data,
                NombreEspecialidad = medico.Data.Especialidad.NombreEspecialidad
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(MedicoViewModel model)
        {
            var medico = await _medicoServices.UpdatearAsync(model.MedicoId,
                new MedicoDTORequest()
                {
                    NombreCompleto = model.NombreCompleto,
                    Matricula = model.Matricula,
                    CedulaProfecional = model.CedulaProfecional,
                    EspecialidadId = model.EspecialidadSeleccionada,
                });
            

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Eliminar(int id)
        {
            var existeMedico = await _medicoServices.FinMedicoByIdAsync(id);

            if(existeMedico is null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new MedicoViewModel()
            {
                MedicoId = id,
                NombreCompleto = existeMedico.Data.NombreCompleto
            };

            return View(model);


        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(MedicoViewModel model)
        {
            var medico = await _medicoServices.EliminarAsync(model.MedicoId);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> MedicosEliminados()
        {
            var listaMedicosEliminados = await _medicoServices.ListarEliminadosAsync();

            return View(listaMedicosEliminados.Data);
        }

        public async Task<IActionResult> Reactivar(int id)
        {
            var existeMedico = await _medicoServices.FinMedicoByIdAsync(id);

            if(existeMedico is null)
            {
                return RedirectToAction(nameof(MedicosEliminados));
            }
            var model = new MedicoViewModel()
            {
                MedicoId = id,
                NombreCompleto = existeMedico.Data.NombreCompleto
            };
            return View(model);


        }

        [HttpPost]
        public async Task<IActionResult> Reactivar(MedicoViewModel model)
        {
            var medico = await _medicoServices.ReactivarAsync(model.MedicoId);

            return RedirectToAction(nameof(MedicosEliminados));


        }

    }
}

MedicoMVC/Views/Medico/Crear.cshtml
@model MedicoMVC.Models.ViewModels.MedicoViewModel

@{
    ViewBag.Title = "Agregar Medico";
    Layout = "_Layout";
}


<section>
    <div class="container">
        <h1>Agregar nuevo Medico</h1>
        <form asp-controller="Medico" asp-action="Crear" method="post">
            <partial name="_FormularioBase" model="Model">
        </form>
    </div>
</section>

@section Scripts {
    @{
        <partial name="_validationScriptsPartial" />
    }
}

MedicoMVC/Views/Medico/Editar.cshtml
@model MedicoMVC.Models.ViewModels.MedicoViewModel

@{
    ViewBag.Title = "Editar Datos del Medico";
    Layout = "_Layout";
}


<section>
    <div class="container">
        <h1>Editar Datos Del Medico: @Model.NombreCompleto</h1>
    <form asp-controller="Medico" asp-action="Editar" method="post">
        <input type="hidden" asp-for="MedicoId">
        <partial name="_FormularioBase" model="Model">
                <div class="col col-sm-5">
                        @Html.LabelFor(m => m.EspecialidadSeleccionada, new { @class = "for-label" })
                        @Html.DropDownListFor(m => m.EspecialidadSeleccionada,
                                 new SelectList(Model.Especialidades, "Id", "NombreEspecialidad"), Model.NombreEspecialidad, new { @class = "form-select" })
                </div>
    </form>
    </div>
</section>

@section Scripts {
    @{
        <partial name="_validationScriptsPartial" />
    }
}

MedicoMVC/Views/Medico/Eliminar.cshtml
@model MedicoMVC.Models.ViewModels.MedicoViewModel

@{
    ViewBag.Title= "Eliminar Medico";
    Layout = "_Layout";
}


<section>
    <div class="container">
        <h1>Esta seguro que desea eliminar al medico: @Model.NombreCompleto</h1>
        <form asp-controller="Medico" asp-action="Eliminar" method="post">
            <input type="hidden" asp-for="MedicoId">
            <div class="row my-3 justify-content-start">
                <div class="col col-auto">
                    <button class="BtnDanger" type="submit">Aceptar<span><i class="bi bi-check"></i></span></button>
                </div>
                <div class="col col-auto">
                    <a class="BtnWarning" asp-controller="Medico" asp-action="index">Cancelar<span><i class="bi bi-exclamation-lg"></i></span></a>
                </div>
            </div>
        </form>
    </div>
</section>

MedicoMVC/Views/Medico/Index.cshtml
@model MedicoMVC.Models.ViewModels.SearchMedicoViewModel

@{
    ViewBag.Title = "Listar Medicos";
    Layout = "_Layout";
}

<section class="myTable">
    <div class="container">
            <form asp-controller="Medico" asp-action="Index" method="get">
                <h1>Lista de Medicos</h1>
                    <div class="row justify-content-start">
                        <div class="col-auto col-sm-5">
                         @Html.LabelFor(p => p.NombreCompleto, new { @class = "for-label" }) 
                         @Html.TextBoxFor(p => p.NombreCompleto, new{ @class="form-control"}) 
                        @* <input type="text" class="form-control" placeholder="Buscar Medico..." name="Nombre" value="@ViewBag.Nombre"> *@
                        </div>
                        <div class="col-auto col-sm-5">
                            @Html.LabelFor(p => p.Matricula, new {@class="for-label"})
                            @Html.TextBoxFor(p => p.Matricula, new {@class= "form-control"})
                        </div>
                        <div class="col-auto ">
                            @Html.LabelFor(p => p.CedulaProfecional, new {@class="for-label" })
                            @Html.TextBoxFor(p => p.CedulaProfecional, new {@class="form-control"})
                        </div>
                        <div class="col-auto ">
                            <div class="inputBox">
                        @* <input type="text" class="form-control" asp-for="NombreCompleto" name="nombreCompleto" value="@ViewBag.nombreCompleto"> *@
                         @* <span>Nombre Completo</span> *@
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-start">
                        <div class="col-auto col-sm-5">
                            <label asp-for="FechaIngresoInicio" class="form-label"></label>
                            <input type="date" asp-for="FechaIngresoInicio" asp-format="dd/MM/yyyy" class="form-control">
                        </div>
                        <div class="col-auto col-sm-5">
                            <label asp-for="FechaIngresoFin" class="form-label"></label>
                            <input type="date" asp-for="FechaIngresoFin" asp-format="dd/MM/yyyy" class="form-control">
                        </div>
                    </div>
                    <div class="row justify-content-start">
                        <div class="col mt-3 col-3">
                            @Html.LabelFor(p => p.EspecialidadSeleccionada, new { @class = "for-label" })
                            @Html.DropDownListFor(m => m.EspecialidadSeleccionada,
                            new SelectList(Model.Especialidades,"Id","NombreEspecialidad"),"Mostrar Todas las Especialidades",new{ @class="form-select"})
                        </div>
                    </div>
                <div class="col-auto mt-3">
                <a class="Btn" asp-controller="Medico" asp-action="Crear">Agregar<span><i class="bi bi-plus-circle"></i></span></a>
                <button class="Btn" type="submit">Buscar<span><i class="bi bi-search"></i></span></button>
                </div>
            </form>
    </div>

    <div class="container text-center mt-4">
        <div class="row mt-4">
            <table class="table table-striped table-hover">
                <thead>
                    <tr class="table-success">
                        <th>Codigo</th>
                        <th>Nombre Completo</th>
                        <th>Fecha Ingreso</th>
                        <th>Matricula</th>
                        <th>Cedula Profesional</th>
                        <th>Especialidad</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Medicos)
                    {
                        <tr>
                            <td>@item.MedicoId</td>
                            <td>@item.NombreCompleto</td>
                            <td>@item.FechaIngreso</td>
                            <td>@item.Matricula</td>
                            <td>@item.CedulaProfecional</td>
                            <td>@item.Especialidad.NombreEspecialidad</td>
                            <td>
                                <a asp-controller="Medico" asp-action="Editar" asp-route-Id="@item.MedicoId"><i class="bi bi-pencil"></i></a>
                                <a asp-controller="Medico" asp-action="Eliminar" asp-route-Id="@item.MedicoId"><i class="bi bi-trash3-fill"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

MedicoMVC/Views/Medico/MedicosEliminados.cshtml
@model ICollection<MedicoMVC.Models.Response.MedicoDTOResponse>

@{
    ViewBag.Title = "Meidcos dados de baja";
    Layout = "_LayOut";
}


<section>
    <div class="container">
        <h1>Lista de Medico que fueron dados de baja</h1>
        <div class="row">
            <div class="col mt-3">
                @if(Model is null)
                {
                    <p>Sin resultados</p>
                }
                else if(!Model.Any())
                {
                    <p>Sin datos para mostrar</p>
                }
                else
                {
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr class="table-success">
                                <th>Codigo</th>
                                <th>Nombre Completo</th>
                                <th>Matricula</th>
                                <th>Cedula Profesional</th>
                                <th>Especialidad</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.MedicoId </td>
                                    <td>@item.NombreCompleto </td>
                                    <td>@item.Matricula </td>
                                    <td>@item.CedulaProfecional </td>
                                    <td>@item.Especialidad </td>
                                    <td>
                                        <a asp-controller="Medico" asp-action="Reactivar" asp-route-Id="@item.MedicoId"><i class="bi bi-bootstrap-reboot"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-auto">
                <a class="Btn" asp-controller="Home" asp-action="Index">Regresar<span><i class="bi bi-plus-circle"></i></span></a>
            </div>
        </div>
    </div>
</section>

MedicoMVC/Views/Medico/Reactivar.cshtml
@model MedicoMVC.Models.ViewModels.MedicoViewModel

@{
    ViewBag.Title = "Reactivar Medico";
    Layout = "_Layout";
}

<section>
    <div class="container">
        <h1> Desea Reactivar al medico: @Model.NombreCompleto</h1>
        <form asp-controller="MedicoPrueba" asp-action="Reactivar" method="post">
            <input type="hidden" asp-for="MedicoId">
            <div class="row justify-content-start">
                <div class="col-auto">
                    <button class="Btn" type="submit">Aceptar<span><i class="bi bi-check"></i></span></button>
                    <a class="BtnWarning" asp-controller="MedicoPrueba" asp-action="MedicosEliminados">Cancelar<span><i class="bi bi-exclamation-lg"></i></span></a>
                </div>
            </div>

        </form>
    </div>
</section>

MedicoMVC/Views/Medico/_FormularioBase.cshtml
@model MedicoMVC.Models.ViewModels.MedicoViewModel

@{
    ViewBag.Title = "Formulario Base";
    Layout = "_Layout";
}

<section>
    <div asp-validation-summary="All" class="text-danger"></div>
        <div class="row">

            <div class="col col-sm-5">
                @Html.LabelFor(m => m.NombreCompleto, new { @class = "for-label" })
                @Html.TextBoxFor(m => m.NombreCompleto, new { @class = "form-control" })
            </div>
            <div class="col col-sm-5">
            @Html.LabelFor(m => m.Matricula, new { @class = "for-label" })
            @Html.TextBoxFor(m => m.Matricula, new { @Class = "form-control" })
            </div>
        </div>
        <div class="row">
        <div class="col col-sm-5">
            @Html.LabelFor(m => m.CedulaProfecional, new { @class = "for-label" })
            @Html.TextBoxFor(m => m.CedulaProfecional, new { @Class = "form-control" })
        </div>
            <div class="col col-sm-5">
                @Html.LabelFor(m => m.EspecialidadSeleccionada, new { @class = "for-label" })
                @Html.DropDownListFor(m => m.EspecialidadSeleccionada,
                         new SelectList(Model.Especialidades, "Id", "NombreEspecialidad"), "Seleccione", new { @class = "form-select"  })
            </div>
        </div>
        <div class="row mt-3 justify-content-end">
            <div class="col-auto ">
                <button class="Btn" type="submit">Aceptar<span><i class="bi bi-check"></i></span></button>
            </div>
            <div class="col-auto">
            <a class="BtnWarning" asp-controller="Medico" asp-action="index">Cancelar<span><i class="bi bi-exclamation-lg"></i></span></a>

            </div>
        </div>
</section>